apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}-banking-service
  name: {{ .Release.Name }}-banking-service
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-banking-service
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-banking-service
    spec:
      containers:
        - image:
            harbor.k8s.elab.rs/banka-1/banking-service:{{ .Values.imageTag}}
          imagePullPolicy: Always
          name: banking-service
{{/*          livenessProbe:*/}}
{{/*            httpGet:*/}}
{{/*              path: /actuator/health*/}}
{{/*              port: 8082*/}}
{{/*            initialDelaySeconds: 60*/}}
{{/*            periodSeconds: 10*/}}
{{/*            failureThreshold: 3*/}}
{{/*          readinessProbe:*/}}
{{/*            httpGet:*/}}
{{/*              path: /actuator/health*/}}
{{/*              port: 8082*/}}
{{/*            initialDelaySeconds: 30*/}}
{{/*            periodSeconds: 10*/}}
{{/*            failureThreshold: 10*/}}
          env:
            - name: THC_PORT
              value: "8082"
            - name: THC_PATH
              value: "/actuator/health"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://{{ .Release.Name}}-primary.{{ .Release.Namespace}}.svc:5432/banking-service-db?useUnicode=true&characterEncoding=UTF-8
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: org.postgresql.Driver
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  key: user
                  name: {{ .Release.Name}}-pguser-banking-service-user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ .Release.Name}}-pguser-banking-service-user
            - name: SPRING_ACTIVEMQ_BROKER_URL
              value: tcp://{{ .Release.Name}}-message-broker:61616?jms.prefetchPolicy.all=1&jms.redeliveryPolicy.maximumRedeliveries=0
            - name: FRONTEND_URL
              value: https://{{ .Values.appDomain }}
            - name: LOGGING_LEVEL_COM_BANKA1_COMMON
              value: WARN
            - name: SPRING_SQL_INIT_MODE
              value: always
            - name: INTERBANK_TARGET_URL
              value: https://banka-4.si.raf.edu.rs/interbank/interbank
            - name: TRADING_SERVICE_URL
              value: http://{{ .Release.Name}}-trading-service:3000
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  key: api_key
                  name: banka-1-interbank
            - name: FOREIGN_BANK_API_KEY
              valueFrom:
                secretKeyRef:
                  key: bank4_api_key
                  name: banka-1-interbank

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name}}-banking-service
  name: {{ .Release.Name}}-banking-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 8082
      protocol: TCP
      targetPort: 8082
  selector:
    app: {{ .Release.Name}}-banking-service
  type: ClusterIP
