apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name}}-trading-service
  name: {{ .Release.Name}}-trading-service
  namespace: {{ .Release.Namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name}}-trading-service
  template:
    metadata:
      labels:
        app: {{ .Release.Name}}-trading-service
    spec:
      containers:
        - image: harbor.k8s.elab.rs/banka-1/trading-service:{{ .Values.imageTag}}
          imagePullPolicy: Always
          name: trading-service
#          livenessProbe:
#            initialDelaySeconds: 180
#            httpGet:
#              port: 8000
#              path: /health
#            periodSeconds: 10
#            failureThreshold: 10
#          readinessProbe:
#            initialDelaySeconds: 30
#            httpGet:
#              port: 8000
#              path: /health
#            periodSeconds: 10
#            failureThreshold: 10
          env:
            - name: POSTGRES_DSN
              valueFrom:
                secretKeyRef:
                  key: uri
                  name: {{ .Release.Name}}-pguser-trading-service-user
            - name: MESSAGE_BROKER_HOST
              value: {{ .Release.Name}}-message-broker:61613
            - name: MESSAGE_BROKER_NETWORK
              value: "tcp"
            - name: USER_SERVICE
              value: http://{{ .Release.Name}}-user-service:8081
            - name: BANKING_SERVICE_URL
              value: http://{{ .Release.Name}}-banking-service:8082
            - name: REDIS_ADDR
              value: {{ .Release.Name}}-redis-master.{{ .Release.Namespace}}.svc:6379
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: redis-password
                  name: banka-1-redis
            - name: BANK1_SECURITY
              valueFrom:
                secretKeyRef:
                  key: bank4_api_key
                  name: banka-1-interbank
            - name: BANK4_API_KEY
              valueFrom:
                secretKeyRef:
                  key: api_key
                  name: banka-1-interbank
            - name: BANK4_BASE_URL
              value: https://banka-4.si.raf.edu.rs/api/interbank
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name}}-trading-service
  name: {{ .Release.Name}}-trading-service
  namespace: {{ .Release.Namespace}}
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: {{ .Release.Name}}-trading-service
  type: ClusterIP
