apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name}}-user-service
  name: {{ .Release.Name}}-user-service
  namespace: {{ .Release.Namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name}}-user-service
  template:
    metadata:
      labels:
        app: {{ .Release.Name}}-user-service
    spec:
      containers:
        - image: harbor.k8s.elab.rs/banka-1/user-service:{{ .Values.imageTag}}
          imagePullPolicy: Always
          name: user-service
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 10
          env:
            - name: THC_PORT
              value: "8081"
            - name: THC_PATH
              value: "/actuator/health"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://{{ .Release.Name}}-primary.{{ .Release.Namespace}}.svc:5432/user-service-db?useUnicode=true&characterEncoding=UTF-8
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: org.postgresql.Driver
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  key: user
                  name: {{ .Release.Name}}-pguser-user-service-user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ .Release.Name}}-pguser-user-service-user
            - name: LOGGING_LEVEL_COM_BANKA1_COMMON
              value: WARN
            - name: SPRING_ACTIVEMQ_BROKER_URL
              value: tcp://{{ .Release.Name}}-message-broker:61616?jms.prefetchPolicy.all=1&jms.redeliveryPolicy.maximumRedeliveries=0
            - name: FRONTEND_URL
              value: {{ .Values.appDomain}}
            - name: SPRING_SQL_INIT_MODE
              value: always

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name}}-user-service
  name: {{ .Release.Name}}-user-service
  namespace: {{ .Release.Namespace}}
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: {{ .Release.Name}}-user-service
  type: ClusterIP
